import { IMessage, IUser } from "types";

export const users: IUser[] = [
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
    {
        name: "Angkush Sahu",
        pic: "",
        _id: "dskafjdkasfjdaskfjkdsf",
        email: "dakfjdaskfjdksfj@kdsfjsdkf.casdklj",
        joinedOn: "12 trh kjsdaf kasdjf dksf",
        userName: "angkush_sahu",
    },
];

export const messages: IMessage[] = [
    { messageBy: "them", text: "lorem ipsum dolor isit amet consectutor." },
    {
        messageBy: "me",
        text: "lorem ipsum dolor isit amet consectutor. lorem ipsum dolor isit amet consectutor.",
    },
    { messageBy: "me", text: "lorem ipsum dolor isit amet consectutor." },
    { messageBy: "me", text: "lorem ipsum dolor isit amet consectutor." },
    {
        messageBy: "me",
        text: "lorem ipsum dolor isit amet consectutor. lorem ipsum dolor isit amet consectutor.",
    },
    { messageBy: "them", text: "lorem ipsum dolor isit amet consectutor." },
    { messageBy: "me", text: "lorem ipsum dolor isit amet consectutor." },
    { messageBy: "them", text: "lorem ipsum dolor isit amet consectutor." },
    { messageBy: "me", text: "lorem ipsum dolor isit amet consectutor." },
];

export const newUsers = [
    { name: "John Doe", email: "johndoe@gmail.com", image: "" },
    { name: "Angkush Sahu", email: "angkushsahu25021982@gmail.com", image: "" },
    { name: "John Doe", email: "johndoe@gmail.com", image: "" },
    { name: "Angkush Sahu", email: "angkushsahu25021982@gmail.com", image: "" },
    { name: "John Doe", email: "johndoe@gmail.com", image: "" },
    { name: "Angkush Sahu", email: "angkushsahu25021982@gmail.com", image: "" },
    { name: "John Doe", email: "johndoe@gmail.com", image: "" },
    { name: "Angkush Sahu", email: "angkushsahu25021982@gmail.com", image: "" },
    { name: "John Doe", email: "johndoe@gmail.com", image: "" },
    { name: "Angkush Sahu", email: "angkushsahu25021982@gmail.com", image: "" },
    { name: "John Doe", email: "johndoe@gmail.com", image: "" },
    { name: "Angkush Sahu", email: "angkushsahu25021982@gmail.com", image: "" },
    { name: "John Doe", email: "johndoe@gmail.com", image: "" },
    { name: "Angkush Sahu", email: "angkushsahu25021982@gmail.com", image: "" },
    { name: "John Doe", email: "johndoe@gmail.com", image: "" },
    { name: "Angkush Sahu", email: "angkushsahu25021982@gmail.com", image: "" },
    { name: "John Doe", email: "johndoe@gmail.com", image: "" },
    { name: "Angkush Sahu", email: "angkushsahu25021982@gmail.com", image: "" },
    { name: "John Doe", email: "johndoe@gmail.com", image: "" },
    { name: "Angkush Sahu", email: "angkushsahu25021982@gmail.com", image: "" },
];
